import Foundation

/// Banco fijo de preguntas de opción múltiple por habilidad — este contenido no lo genera la IA:
/// son los dos tests entregados por el usuario, transcritos tal cual:
/// - "TEST INTEGRAL DE NIVEL EN GUITARRA ELÉCTRICA" (técnica): 18 habilidades, 90 preguntas,
///   5 opciones A-E con puntaje 0-4 cada una (escala de dominio, no de correcto/incorrecto).
/// - "TEST INTEGRAL DE TEORÍA MUSICAL APLICADA A LA GUITARRA ELÉCTRICA" (teoría): 20 módulos,
///   100 preguntas, 4 opciones A-D con una sola correcta (1 punto) + una 5ª opción "No lo sé"
///   agregada a pedido del usuario para distinguir no saber de adivinar y fallar.
/// Las preguntas aparecen al instante sin depender de Ollama, y el puntaje/nivel es el que
/// definió el propio documento, no uno inventado aquí.
enum SkillAssessmentQuestionBank {
    static func questions(for skillName: String) -> [AssessmentQuestion] {
        (techniqueBank[skillName] ?? theoryBank[skillName]) ?? []
    }

    /// Construye una pregunta de técnica: 5 opciones con el puntaje estándar del test (A=0, B=1, C=2, D=3, E=4).
    private static func q(_ question: String, _ a: String, _ b: String, _ c: String, _ d: String, _ e: String) -> AssessmentQuestion {
        AssessmentQuestion(question: question, options: [
            AssessmentOption(text: a, points: 0),
            AssessmentOption(text: b, points: 1),
            AssessmentOption(text: c, points: 2),
            AssessmentOption(text: d, points: 3),
            AssessmentOption(text: e, points: 4)
        ])
    }

    /// Construye una pregunta de teoría: 4 opciones de las cuales una es correcta (1 punto, según
    /// `correct`), más una 5ª opción "No lo sé" (0 puntos) para no confundir con adivinar y fallar.
    private static func tq(_ question: String, _ a: String, _ b: String, _ c: String, _ d: String, correct: Character) -> AssessmentQuestion {
        let letters: [Character] = ["A", "B", "C", "D"]
        let texts = [a, b, c, d]
        var options = zip(letters, texts).map { letter, text in
            AssessmentOption(text: text, points: letter == correct ? 1 : 0)
        }
        options.append(AssessmentOption(text: "No lo sé.", points: 0))
        return AssessmentQuestion(question: question, options: options)
    }

    private static let techniqueBank: [String: [AssessmentQuestion]] = [
        "Postura, relajación y mecánica general": [
            q("¿Qué ocurre después de tocar durante veinte minutos?",
              "Siento dolor, hormigueo o debo detenerme.",
              "Siento tensión intensa y pierdo precisión.",
              "Termino cansado, pero puedo continuar con varios errores.",
              "Mantengo una tensión leve que desaparece al descansar.",
              "Puedo continuar relajado, sin dolor ni pérdida de precisión."),
            q("¿Cuánta presión utilizas con la mano izquierda?",
              "Aprieto todo lo posible para evitar trasteos.",
              "Aprieto mucho y el pulgar queda rígido.",
              "Puedo reducir la presión lentamente, pero vuelvo a apretar al acelerar.",
              "Utilizo poca presión en ejercicios y canciones moderadas.",
              "Utilizo la presión mínima necesaria incluso al tocar rápido o hacer cambios."),
            q("¿Qué sucede con tus dedos al tocar una escala?",
              "Se levantan varios centímetros del diapasón.",
              "Los dedos se alejan mucho y pierdo tiempo al regresar.",
              "Algunos dedos permanecen cerca, pero otros se elevan demasiado.",
              "La mayoría permanece cerca del diapasón.",
              "Todos se desplazan eficientemente sin tensión ni movimientos innecesarios."),
            q("¿Qué ocurre cuando aumentas el tempo?",
              "Aprieto más y pierdo completamente el control.",
              "Los movimientos se vuelven grandes y tensos.",
              "Puedo tocar más rápido, pero aparece tensión moderada.",
              "Mantengo movimientos pequeños hasta cerca de mi límite.",
              "Aumento la velocidad sin cambios importantes de postura, presión o relajación."),
            q("Cuando aparece tensión, ¿cómo reaccionas?",
              "Continúo hasta terminar el ejercicio.",
              "Sacudo las manos y vuelvo a tocar igual.",
              "Bajo el tempo, pero no identifico la causa.",
              "Identifico la zona tensa y ajusto postura o movimiento.",
              "Identifico la causa mediante grabación, corrijo el movimiento y verifico que la tensión no reaparezca.")
        ],

        "Sincronización entre ambas manos": [
            q("Al tocar una escala lentamente, ¿cómo comienzan las notas?",
              "Muchas notas quedan apagadas o no suenan.",
              "Escucho ataques dobles o espacios frecuentes.",
              "La mayoría suena, pero aparecen varios desfases.",
              "Cuatro de cinco ejecuciones suenan coordinadas.",
              "Todas las notas comienzan definidas en diferentes posiciones y velocidades."),
            q("¿Qué ocurre cuando cambias de cuerda?",
              "Me detengo o pierdo completamente la coordinación.",
              "Golpeo cuerdas equivocadas con frecuencia.",
              "Consigo el cambio lentamente, pero con pausas pequeñas.",
              "Cambio de cuerda limpiamente en ejercicios moderados.",
              "Mantengo sincronización, dinámica y ritmo en cambios complejos."),
            q("¿Puedes tocar el ejercicio extremadamente lento?",
              "No; tocar lento me resulta más difícil que tocar rápido.",
              "Pierdo el pulso y hago movimientos desordenados.",
              "Puedo hacerlo, pero aparecen espacios entre notas.",
              "Puedo tocarlo lentamente con coordinación estable.",
              "Puedo detenerme en cualquier nota y reiniciar sin alterar la mecánica."),
            q("¿Puedes reconocer qué mano provoca un error?",
              "No sé cuál fue la causa.",
              "Normalmente culpo a la mano que siento más débil.",
              "Puedo identificar algunos errores evidentes.",
              "Distingo errores de púa, digitación y sincronización.",
              "Puedo identificar la causa mediante audio o video y formular una corrección concreta."),
            q("¿Qué sucede cerca de tu velocidad máxima?",
              "Ambas manos pierden totalmente el control.",
              "Una mano se adelanta claramente.",
              "Mantengo las notas, pero con varios desajustes.",
              "Mantengo cuatro de cinco intentos coordinados.",
              "Puedo permanecer cerca de mi máximo con precisión, relajación y control dinámico.")
        ],

        "Ritmo, subdivisión y groove": [
            q("¿Puedes tocar negras durante dos minutos con metrónomo?",
              "Pierdo el pulso antes de treinta segundos.",
              "Me adelanto o atraso constantemente.",
              "Mantengo el pulso aproximadamente, con varias correcciones.",
              "Mantengo cuatro de cinco intentos estables.",
              "Mantengo el pulso y puedo variar dinámica sin cambiar el tempo."),
            q("¿Cómo manejas negras, corcheas, tresillos y semicorcheas?",
              "No sé distinguirlas.",
              "Las reconozco, pero no puedo ejecutarlas correctamente.",
              "Puedo ejecutar algunas lentamente.",
              "Puedo cambiar entre ellas manteniendo el pulso.",
              "Puedo combinarlas, acentuarlas y aplicarlas dentro de riffs o solos."),
            q("¿Qué ocurre durante cambios de acorde o posición?",
              "Me detengo completamente.",
              "Pierdo varios pulsos.",
              "El tempo disminuye temporalmente.",
              "Mantengo el tempo en cambios habituales.",
              "Mantengo el tempo, la dinámica y el groove incluso en cambios complejos."),
            q("¿Puedes tocar con el metrónomo marcando solamente los tiempos 2 y 4?",
              "No entiendo cómo hacerlo.",
              "Me pierdo rápidamente.",
              "Puedo hacerlo en patrones muy sencillos.",
              "Mantengo un acompañamiento moderado sin perderme.",
              "Puedo tocar riffs, acordes e improvisaciones sintiendo internamente los tiempos restantes."),
            q("¿Puedes identificar tu posición respecto del pulso?",
              "No escucho si voy adelantado o atrasado.",
              "Solo lo noto cuando el desfase es muy grande.",
              "Lo detecto después de escuchar una grabación.",
              "Lo detecto mientras estoy tocando.",
              "Puedo tocar intencionalmente delante, detrás o sobre el pulso sin perder estabilidad.")
        ],

        "Acordes y guitarra rítmica": [
            q("¿Cómo realizas cambios entre acordes abiertos?",
              "Debo detenerme para colocar los dedos.",
              "Cambio con pausas frecuentes.",
              "Cambio lentamente, pero pierdo algunos pulsos.",
              "Mantengo el ritmo en canciones moderadas.",
              "Mantengo ritmo, dinámica y articulación en diferentes patrones."),
            q("¿Cómo suenan tus cejillas?",
              "Varias cuerdas no suenan.",
              "Solo funcionan si aprieto con mucha fuerza.",
              "Funcionan en algunas posiciones.",
              "Suenan limpias en la mayoría del mástil con tensión baja.",
              "Puedo cambiarlas rápidamente, variar inversiones y controlar cada cuerda."),
            q("¿Cómo ejecutas power chords?",
              "Suenan cuerdas abiertas o notas equivocadas.",
              "Puedo hacer la forma, pero con ruido.",
              "Funcionan lentamente y en pocas posiciones.",
              "Puedo desplazarlos manteniendo ritmo y limpieza.",
              "Puedo combinar desplazamientos, palm mute, silencios y diferentes acentos."),
            q("¿Puedes controlar qué cuerdas golpea la púa?",
              "Golpeo todas las cuerdas.",
              "Intento limitar el ataque, pero fallo con frecuencia.",
              "Puedo seleccionar grupos amplios de cuerdas.",
              "Golpeo solamente las cuerdas necesarias en la mayoría de los acordes.",
              "Puedo seleccionar cuerdas, inversiones y voces internas con precisión dinámica."),
            q("¿Puedes tocar una parte rítmica completa?",
              "Solo puedo tocar fragmentos.",
              "Me detengo varias veces.",
              "Completo partes sencillas con algunos errores.",
              "Completo canciones moderadas manteniendo la estructura.",
              "Mantengo canciones completas con groove, dinámica, cortes y consistencia.")
        ],

        "Muting y palm muting": [
            q("¿Qué ocurre al tocar una escala con distorsión?",
              "Suenan muchas cuerdas adicionales.",
              "Aparecen resonancias después de casi cada cambio.",
              "Puedo controlar parte del ruido lentamente.",
              "Mantengo cuatro de cinco intentos limpios.",
              "Mantengo limpieza con diferentes ganancias, posiciones y articulaciones."),
            q("¿Puedes detener todas las cuerdas inmediatamente?",
              "Continúan resonando varias cuerdas.",
              "Necesito varios movimientos para detenerlas.",
              "Puedo detenerlas lentamente.",
              "Puedo producir silencios definidos dentro de riffs.",
              "Puedo controlar silencios muy breves y precisos sin alterar el tempo."),
            q("¿Cómo controlas las cuerdas graves durante un solo?",
              "No las controlo.",
              "Confío principalmente en una puerta de ruido.",
              "Las controlo en algunas posiciones.",
              "La mano derecha las silencia de manera consistente.",
              "Combino ambas manos y adapto el muting a cada cambio de cuerda."),
            q("¿Cómo utilizas el palm muting?",
              "No sé dónde apoyar la mano.",
              "Las notas quedan completamente apagadas.",
              "Consigo un único sonido de palm mute.",
              "Puedo variar entre abierto, moderado y cerrado.",
              "Puedo controlar gradualmente ataque, sustain y dinámica sin perder afinación."),
            q("¿Qué ocurre al aumentar la ganancia?",
              "El ruido hace imposible distinguir las notas.",
              "Necesito cerrar completamente la puerta de ruido.",
              "Puedo tocar algunos fragmentos limpios.",
              "Mantengo control en riffs y escalas moderados.",
              "La mayor ganancia revela pocos ruidos y puedo identificar inmediatamente su origen.")
        ],

        "Alternate picking": [
            q("¿Puedes mantener abajo-arriba de manera continua?",
              "Pierdo la alternancia inmediatamente.",
              "La mantengo solamente en una cuerda y lentamente.",
              "La mantengo en patrones sencillos con algunos errores.",
              "La mantengo en escalas y riffs moderados.",
              "La mantengo en frases complejas, diferentes acentos y cambios de cuerda."),
            q("¿Cómo suenan los ataques ascendentes respecto de los descendentes?",
              "Los ascendentes casi no suenan.",
              "Suenan considerablemente más débiles.",
              "Son parecidos a velocidad lenta.",
              "Son uniformes en velocidades moderadas.",
              "Puedo igualarlos o diferenciarlos intencionalmente mediante dinámica."),
            q("¿Puedes comenzar una frase con ataque ascendente?",
              "No sé hacerlo.",
              "Me desoriento inmediatamente.",
              "Puedo hacerlo lentamente.",
              "Puedo comenzar en ambas direcciones en ejercicios moderados.",
              "Puedo elegir el ataque inicial según los cambios de cuerda y los acentos."),
            q("¿Qué ocurre al cambiar de cuerda?",
              "Golpeo varias cuerdas equivocadas.",
              "Debo detener el movimiento.",
              "Cambio lentamente con algunos roces.",
              "Cambio limpiamente en patrones habituales.",
              "Controlo cambios interiores, exteriores y diferentes agrupaciones."),
            q("¿Cómo se comporta tu movimiento cerca del tempo máximo?",
              "Utilizo todo el brazo.",
              "El movimiento se amplía y se vuelve rígido.",
              "Mantengo cierta velocidad, pero con tensión.",
              "El movimiento permanece pequeño en cuatro de cinco intentos.",
              "Puedo tocar cerca de mi máximo sin perder relajación, dinámica ni precisión.")
        ],

        "Downpicking, tremolo picking y gallops": [
            q("¿Puedes mantener downpicking durante ocho compases?",
              "Me detengo antes de completar dos compases.",
              "Completo el patrón con tensión y pérdida de pulso.",
              "Lo mantengo lentamente con fatiga moderada.",
              "Mantengo cuatro de cinco intentos estables.",
              "Mantengo ataque, groove y dinámica durante partes completas."),
            q("¿Qué ocurre con tu hombro y antebrazo?",
              "Se bloquean rápidamente.",
              "Siento tensión intensa.",
              "Aparece tensión al aumentar el tempo.",
              "Mantengo tensión baja en tempos moderados.",
              "Puedo ajustar el esfuerzo y recuperarme sin perder el patrón."),
            q("¿Puedes ejecutar gallops?",
              "No distingo el patrón.",
              "Lo reconozco, pero lo ejecuto irregularmente.",
              "Puedo tocar gallops sencillos lentamente.",
              "Puedo tocar gallops y gallops invertidos con metrónomo.",
              "Puedo combinarlos con cambios de cuerda, acentos y palm muting."),
            q("¿Puedes mantener tremolo picking durante treinta segundos?",
              "No puedo mantenerlo.",
              "Acelero y freno constantemente.",
              "Mantengo una velocidad moderada con algunas irregularidades.",
              "Mantengo cuatro de cinco intentos uniformes.",
              "Puedo controlar tempo, volumen y cambios de cuerda."),
            q("¿Puedes hacer crescendos sin cambiar el tempo?",
              "Al tocar más fuerte también acelero.",
              "Pierdo regularidad al cambiar el volumen.",
              "Puedo hacerlo lentamente.",
              "Puedo variar la intensidad conservando el pulso.",
              "Puedo controlar crescendos, diminuendos y acentos dentro de riffs reales.")
        ],

        "Legato": [
            q("¿Cómo suenan tus hammer-ons?",
              "La mayoría no produce una nota clara.",
              "Son mucho más débiles que las notas pulsadas.",
              "Funcionan con los dedos fuertes y lentamente.",
              "Tienen volumen uniforme en patrones moderados.",
              "Puedo controlar volumen, acentos y dinámica con todos los dedos."),
            q("¿Cómo suenan tus pull-offs?",
              "La nota inferior no aparece.",
              "Saco la cuerda de afinación.",
              "Funcionan lentamente con irregularidad.",
              "Son claros y afinados en cuatro de cinco intentos.",
              "Puedo controlar su intensidad y combinarlos en frases complejas."),
            q("¿Puedes utilizar los dedos anular y meñique?",
              "No consigo producir notas claras.",
              "Solo funcionan con mucha fuerza.",
              "Funcionan lentamente, pero se cansan rápido.",
              "Funcionan en secuencias moderadas con tensión baja.",
              "Poseen independencia, volumen y control comparables con los demás dedos."),
            q("¿Cómo es el ritmo de tus frases de legato?",
              "Las notas aparecen sin subdivisión reconocible.",
              "Los grupos aceleran y frenan.",
              "Puedo mantener subdivisiones lentamente.",
              "Mantengo ritmo estable con metrónomo.",
              "Puedo acentuar diferentes notas y cambiar agrupaciones sin perder el pulso."),
            q("¿Puedes utilizar legato dentro de música real?",
              "No puedo aplicarlo.",
              "Solo conozco un ejercicio.",
              "Puedo insertar un patrón memorizado.",
              "Puedo utilizarlo en solos y melodías sencillas.",
              "Puedo controlar fraseo, dinámica, duración y mezcla con ataques de púa.")
        ],

        "Slides y cambios de posición": [
            q("¿Llegas directamente al traste objetivo?",
              "Suelo terminar en otro traste.",
              "Debo corregir después de llegar.",
              "Llego correctamente en slides cortos y lentos.",
              "Llego correctamente en diferentes distancias.",
              "Puedo hacerlo sin mirar y dentro de frases rítmicas complejas."),
            q("¿El slide permanece dentro del pulso?",
              "No controlo su duración.",
              "Llego tarde con frecuencia.",
              "Puedo sincronizarlo lentamente.",
              "Empieza y termina correctamente en cuatro de cinco intentos.",
              "Puedo variar deliberadamente velocidad, duración y acento."),
            q("¿Qué hace tu pulgar durante el desplazamiento?",
              "Permanece bloqueado.",
              "Produce tensión y limita el movimiento.",
              "Se desplaza en cambios sencillos.",
              "Acompaña la mano sin tensión importante.",
              "Se adapta automáticamente a diferentes posiciones y extensiones."),
            q("¿Puedes realizar cambios silenciosos de posición?",
              "Siempre escucho arrastre de cuerdas.",
              "El ruido es considerable.",
              "Puedo reducirlo lentamente.",
              "Los cambios son limpios en la mayoría de las frases.",
              "Puedo elegir entre un desplazamiento audible o completamente silencioso."),
            q("¿Puedes usar diferentes dedos?",
              "Solo puedo deslizar con un dedo.",
              "Los otros dedos pierden afinación o control.",
              "Puedo utilizar dos dedos en posiciones sencillas.",
              "Puedo utilizar todos los dedos en distancias moderadas.",
              "Puedo seleccionar el dedo según la digitación siguiente y el fraseo.")
        ],

        "Bending": [
            q("¿Cómo afinas bends de medio tono?",
              "No puedo elevar la nota correctamente.",
              "Quedo lejos de la nota objetivo.",
              "Me acerco después de varias correcciones.",
              "Llego afinado en cuatro de cinco intentos.",
              "Llego directamente, sostengo la nota y puedo hacerlo en varias zonas del mástil."),
            q("¿Cómo afinas bends de un tono?",
              "No puedo realizarlos.",
              "Normalmente quedan bajos o altos.",
              "Llego con ayuda de correcciones auditivas.",
              "Llego afinado en cuatro de cinco intentos.",
              "Puedo llegar directamente, variar la velocidad y mantener el sustain."),
            q("¿Puedes sostener la afinación?",
              "La cuerda baja inmediatamente.",
              "La nota oscila sin control.",
              "Puedo sostenerla brevemente.",
              "La mantengo estable durante varios segundos.",
              "Puedo sostenerla y añadir vibrato controlado."),
            q("¿Cómo controlas las cuerdas vecinas?",
              "Suenan varias cuerdas adicionales.",
              "Aparecen ruidos frecuentes al subir o bajar.",
              "Puedo controlarlas lentamente.",
              "Las controlo en la mayoría de los bends.",
              "Puedo silenciarlas durante bends, releases, unísonos y prebends."),
            q("¿Puedes reconocer si el bend está bajo o alto?",
              "No puedo reconocerlo.",
              "Solo noto errores muy grandes.",
              "Lo reconozco usando un afinador.",
              "Lo reconozco auditivamente en una grabación.",
              "Lo detecto y corrijo inmediatamente mientras toco.")
        ],

        "Vibrato": [
            q("¿Cómo es la regularidad de tu vibrato?",
              "La cuerda se mueve sin patrón.",
              "El vibrato tiembla y cambia constantemente.",
              "Es regular solamente a una velocidad.",
              "Mantengo una oscilación estable en cuatro de cinco intentos.",
              "Puedo sincronizarlo, variar su velocidad y mantenerlo musical."),
            q("¿Puedes controlar la amplitud?",
              "No sé distinguir vibrato estrecho y ancho.",
              "La amplitud cambia accidentalmente.",
              "Puedo hacer una amplitud moderada.",
              "Puedo elegir entre vibrato estrecho y ancho.",
              "Puedo modificar gradualmente la amplitud según el estilo y la frase."),
            q("¿La nota regresa al centro de afinación?",
              "La afinación queda desplazada.",
              "Regresa de manera irregular.",
              "Regresa correctamente a velocidad lenta.",
              "Regresa de manera consistente.",
              "Puedo controlar el centro incluso en vibratos amplios o lentos."),
            q("¿Puedes añadir vibrato después de sostener una nota recta?",
              "Siempre comienzo moviendo la cuerda.",
              "No controlo el momento de inicio.",
              "Puedo retrasarlo brevemente.",
              "Puedo elegir cuándo comienza.",
              "Puedo desarrollar la nota mediante diferentes entradas, intensidades y finales."),
            q("¿Puedes realizar vibrato sobre un bend?",
              "El bend pierde completamente la afinación.",
              "La nota cae considerablemente.",
              "Puedo hacerlo lentamente con pequeñas oscilaciones.",
              "Mantengo el bend afinado y añado vibrato.",
              "Controlo amplitud, velocidad y centro de afinación sobre diferentes bends.")
        ],

        "String skipping": [
            q("¿Puedes saltar una cuerda?",
              "Golpeo varias cuerdas equivocadas.",
              "Lo consigo ocasionalmente.",
              "Lo consigo lentamente en patrones repetidos.",
              "Lo consigo limpiamente en cuatro de cinco intentos.",
              "Puedo hacerlo en diferentes patrones, tempos y dinámicas."),
            q("¿Puedes saltar dos o más cuerdas?",
              "No puedo localizar la cuerda objetivo.",
              "Necesito mirar y detenerme.",
              "Puedo hacerlo lentamente.",
              "Puedo hacerlo con precisión moderada.",
              "Puedo hacerlo rápidamente sin mirar constantemente."),
            q("¿Mantienes la alternancia?",
              "Pierdo completamente el patrón de púa.",
              "Cambio de dirección accidentalmente.",
              "Mantengo la alternancia lentamente.",
              "La mantengo en patrones ascendentes y descendentes.",
              "Puedo comenzar desde ambos ataques y conservar los acentos."),
            q("¿Cómo controlas las cuerdas no utilizadas?",
              "Permanecen resonando.",
              "Aparecen ruidos frecuentes.",
              "Puedo reducirlos lentamente.",
              "Mantengo limpieza en la mayoría de los patrones.",
              "Mantengo control total con sonido limpio y distorsionado."),
            q("¿Puedes aplicar string skipping musicalmente?",
              "No conozco ninguna aplicación.",
              "Solo puedo hacer un ejercicio.",
              "Puedo tocar un patrón memorizado.",
              "Puedo utilizarlo en arpegios o melodías.",
              "Puedo improvisar y crear frases sin que el recurso suene mecánico.")
        ],

        "Economy picking": [
            q("¿Comprendes cuándo continuar en la misma dirección?",
              "No conozco la diferencia con alternate picking.",
              "Reconozco el término, pero no puedo explicarlo.",
              "Comprendo el principio en patrones sencillos.",
              "Puedo identificar los cambios económicos antes de tocar.",
              "Puedo diseñar digitaciones según la dirección de la púa."),
            q("¿Puedes atravesar dos cuerdas en la misma dirección?",
              "Las notas suenan como un acorde desordenado.",
              "Pierdo una de las notas.",
              "Puedo hacerlo lentamente.",
              "Las notas quedan separadas en cuatro de cinco intentos.",
              "Mantengo separación, dinámica y ritmo en varias cuerdas."),
            q("¿Puedes tocar patrones ascendentes y descendentes?",
              "No puedo completar ninguno.",
              "Solo puedo tocar una dirección.",
              "Puedo tocar ambas lentamente.",
              "Puedo tocarlas con claridad moderada.",
              "Ambas direcciones tienen velocidad y control semejantes."),
            q("¿Puedes cambiar conscientemente entre alternate y economy?",
              "Los mezclo sin darme cuenta.",
              "Sé que cambio, pero no puedo controlarlo.",
              "Puedo elegir en ejercicios lentos.",
              "Puedo elegir según la frase.",
              "Puedo comparar ambos sistemas y seleccionar el más eficiente sin perder musicalidad."),
            q("¿La técnica reduce realmente tu esfuerzo?",
              "Produce más tensión y errores.",
              "Solo aumenta mi velocidad de manera desordenada.",
              "Reduce algunos movimientos, pero perjudica el ritmo.",
              "Reduce esfuerzo sin perder claridad.",
              "Mejora eficiencia, acentos y fraseo en diferentes contextos.")
        ],

        "Sweep picking": [
            q("¿Las notas suenan separadas?",
              "Suenan como un acorde.",
              "Varias notas se superponen.",
              "Puedo separarlas lentamente en tres cuerdas.",
              "Se separan claramente en cuatro de cinco intentos.",
              "Controlo duración, dinámica y separación en arpegios amplios."),
            q("¿Puedes barrer lentamente?",
              "Solo puedo mover la púa rápidamente y sin control.",
              "Al reducir el tempo pierdo el movimiento.",
              "Puedo hacerlo lentamente con pausas.",
              "Puedo mantener un movimiento continuo y controlado.",
              "Puedo detenerme en cualquier nota y continuar sin alterar la técnica."),
            q("¿Cómo se sincronizan ambas manos?",
              "Las notas aparecen antes o después del ataque.",
              "Hay numerosos huecos y superposiciones.",
              "La sincronización funciona lentamente.",
              "Funciona en cuatro de cinco intentos moderados.",
              "Se mantiene en diferentes formas, velocidades y cambios de dirección."),
            q("¿Puedes ejecutar ascenso y descenso?",
              "No puedo completar el arpegio.",
              "Solo una dirección funciona.",
              "Ambas funcionan lentamente.",
              "Tienen claridad semejante.",
              "Puedo controlar los cambios de dirección sin alterar ritmo ni dinámica."),
            q("¿Puedes aplicar sweep dentro de una frase?",
              "No puedo usarlo musicalmente.",
              "Solo puedo tocar una forma aislada.",
              "Puedo insertar un arpegio memorizado.",
              "Puedo conectarlo con escalas o legato.",
              "Puedo utilizar arpegios diferentes según la armonía y el fraseo.")
        ],

        "Tapping": [
            q("¿Cómo suena la nota golpeada?",
              "No produce una nota clara.",
              "Es mucho más fuerte o débil que las demás.",
              "Se equilibra lentamente.",
              "Tiene volumen uniforme en cuatro de cinco intentos.",
              "Puedo controlar su acento y dinámica dentro de frases."),
            q("¿Qué ocurre al retirar el dedo?",
              "La nota siguiente no suena.",
              "La cuerda queda desafinada lateralmente.",
              "La retirada funciona lentamente.",
              "La nota siguiente aparece clara y afinada.",
              "Puedo controlar diferentes articulaciones y velocidades de retirada."),
            q("¿Cómo controlas el ruido?",
              "Suenan todas las cuerdas.",
              "Dependo completamente de un amortiguador.",
              "Puedo controlar algunos patrones.",
              "Ambas manos mantienen limpieza razonable.",
              "Puedo cambiar de cuerda y posición sin generar resonancias."),
            q("¿Puedes utilizar varios dedos de la mano derecha?",
              "No puedo utilizar tapping.",
              "Solo utilizo un dedo de manera inestable.",
              "Utilizo un dedo con control básico.",
              "Puedo añadir un segundo dedo en patrones sencillos.",
              "Puedo utilizar varios dedos independientemente y con volumen uniforme."),
            q("¿Puedes utilizar tapping musicalmente?",
              "No puedo aplicarlo.",
              "Solo conozco el patrón clásico repetido.",
              "Puedo tocar algunos patrones memorizados.",
              "Puedo utilizarlo en arpegios o melodías.",
              "Puedo crear frases siguiendo la armonía, con dinámica y desarrollo.")
        ],

        "Armónicos": [
            q("¿Puedes producir armónicos naturales en los trastes 12, 7 y 5?",
              "No consigo que suenen.",
              "Suenan de manera accidental.",
              "Suenan claramente en el traste 12.",
              "Suenan claramente en los tres puntos.",
              "Puedo producirlos en diferentes cuerdas y utilizarlos musicalmente."),
            q("¿Puedes producir pinch harmonics?",
              "No comprendo el movimiento.",
              "Aparecen accidentalmente.",
              "Puedo producirlos en una cuerda y posición.",
              "Puedo repetirlos en varias cuerdas.",
              "Puedo seleccionar diferentes armónicos moviendo la zona de ataque."),
            q("¿Dependes de mucha distorsión?",
              "Ni con distorsión aparecen.",
              "Solo aparecen con ganancia extrema.",
              "Aparecen con distorsión moderada.",
              "Puedo producirlos con crunch.",
              "Puedo producirlos limpiamente mediante precisión técnica."),
            q("¿Puedes añadir bend o vibrato?",
              "El armónico desaparece inmediatamente.",
              "Pierdo la afinación o el sustain.",
              "Puedo hacer un movimiento pequeño.",
              "Puedo aplicar bend o vibrato controlado.",
              "Puedo combinar ambos y mantener afinación, sustain y dinámica."),
            q("¿Puedes utilizar armónicos según la música?",
              "No sé cuándo utilizarlos.",
              "Los utilizo aleatoriamente.",
              "Los utilizo como efecto en algunas canciones.",
              "Puedo seleccionar el tipo de armónico según la frase.",
              "Comprendo su afinación, función y relación con el contexto armónico.")
        ],

        "Hybrid picking, fingerstyle y palanca": [
            q("¿Cómo equilibras la púa y los dedos?",
              "No puedo combinarlos.",
              "Los dedos casi no suenan.",
              "Puedo equilibrarlos lentamente.",
              "Mantengo un volumen parecido en patrones moderados.",
              "Puedo controlar independientemente dinámica, articulación y acentos."),
            q("¿Puedes tocar cuerdas no adyacentes simultáneamente?",
              "Golpeo cuerdas equivocadas.",
              "Las notas llegan en momentos diferentes.",
              "Puedo hacerlo lentamente.",
              "Las notas llegan juntas y limpias.",
              "Puedo aplicarlo en acordes, dobles notas y melodías."),
            q("¿Puedes mantener bajo y melodía con fingerstyle?",
              "No puedo separar las voces.",
              "Una voz se detiene cuando comienza la otra.",
              "Puedo hacerlo en patrones muy sencillos.",
              "Mantengo bajo y melodía durante fragmentos moderados.",
              "Puedo controlar independientemente ritmo, dinámica y duración de ambas voces."),
            q("¿Puedes utilizar la palanca y regresar a la afinación?",
              "No utilizo palanca o pierdo totalmente la afinación.",
              "Regreso aproximadamente.",
              "Puedo hacer pequeños movimientos.",
              "Puedo realizar vibrato y regresar correctamente.",
              "Puedo controlar scoops, caídas, vibrato y efectos sincronizados."),
            q("¿Puedes distinguir un error técnico de un problema de ajuste?",
              "No sé diferenciarlos.",
              "Supongo que todos los problemas son del puente.",
              "Reconozco algunos problemas evidentes.",
              "Puedo revisar afinación, retorno, cuerdas y técnica.",
              "Puedo diagnosticar sistemáticamente la causa antes de modificar el instrumento.")
        ],

        "Aplicación musical, oído, teoría y repertorio": [
            q("¿Cuántas canciones completas puedes tocar sin detenerte?",
              "Ninguna.",
              "Una canción muy sencilla con varios errores.",
              "Entre dos y cuatro canciones sencillas.",
              "Al menos cinco canciones completas de dificultad moderada.",
              "Mantengo un repertorio variado con estructura, dinámica y consistencia."),
            q("¿Puedes tocar con una pista o con otros músicos?",
              "Me pierdo inmediatamente.",
              "Necesito detenerme para recuperar la posición.",
              "Puedo seguir canciones sencillas.",
              "Mantengo estructura y tempo en diferentes canciones.",
              "Escucho, reacciono, ajusto dinámica y recupero errores sin detenerme."),
            q("¿Cómo utilizas escalas y arpegios?",
              "No conozco ninguno.",
              "Memorizo formas sin saber qué notas contienen.",
              "Conozco algunas formas y sus tonalidades.",
              "Puedo relacionarlas con acordes y centros tonales.",
              "Puedo seleccionar notas según cada acorde, tensión y resolución."),
            q("¿Puedes reproducir una melodía sencilla de oído?",
              "No puedo encontrar las notas.",
              "Encuentro alguna nota por ensayo y error.",
              "Puedo reproducir frases cortas lentamente.",
              "Puedo reproducir melodías sencillas completas.",
              "Puedo reconocer intervalos, tonalidad, acordes y articulaciones principales."),
            q("¿Cómo analizas tus grabaciones?",
              "No me grabo.",
              "Me grabo, pero solo evalúo si me gusta.",
              "Detecto errores generales.",
              "Identifico problemas de ritmo, limpieza, afinación y técnica.",
              "Identifico la causa probable, diseño una corrección y compruebo si funcionó.")
        ]
    ]

    private static let theoryBank: [String: [AssessmentQuestion]] = [
        "Notas musicales y organización del diapasón": [
            tq("¿Cuál es la afinación estándar desde la sexta cuerda hasta la primera?",
               "E – A – D – G – B – E", "E – B – D – G – A – E", "D – A – D – G – B – E", "E – A – C – G – B – E", correct: "A"),
            tq("¿Cuánto aumenta la afinación al avanzar un traste?",
               "Un tono", "Un semitono", "Una tercera menor", "Una octava", correct: "B"),
            tq("¿Qué nota se encuentra en el quinto traste de la sexta cuerda?",
               "G", "G♯", "A", "B♭", correct: "C"),
            tq("¿Entre cuáles notas naturales existe un semitono?",
               "C-D y F-G", "A-B y D-E", "B-C y E-F", "G-A y C-D", correct: "C"),
            tq("Si tienes un G en el tercer traste de la sexta cuerda, ¿dónde está una octava superior cercana?",
               "Quinto traste de la cuarta cuerda", "Tercer traste de la quinta cuerda", "Séptimo traste de la quinta cuerda", "Primer traste de la tercera cuerda", correct: "A")
        ],

        "Alteraciones y notas enarmónicas": [
            tq("¿Qué efecto tiene un sostenido?",
               "Eleva la nota un tono", "Eleva la nota un semitono", "Reduce la nota un semitono", "Reduce la nota un tono", correct: "B"),
            tq("¿Cuál pareja representa notas enarmónicas?",
               "C y D", "E y F", "F♯ y G♭", "A y C", correct: "C"),
            tq("¿Cuál escritura es correcta para la escala de D mayor?",
               "D – E – G♭ – G – A – B – D♭", "D – E – F♯ – G – A – B – C♯", "D – F♭ – F♯ – G – A – C♭ – C♯", "D – E – F♯ – G♯ – A – B – C", correct: "B"),
            tq("¿Qué nota está un semitono por debajo de B?",
               "A", "A♯ o B♭", "C", "C♭ únicamente", correct: "B"),
            tq("¿Por qué puede ser importante distinguir C♯ de D♭?",
               "Porque siempre producen frecuencias diferentes en la guitarra", "Porque pertenecen a octavas diferentes", "Porque su nombre expresa su función dentro de una escala o acorde", "Porque D♭ solo puede tocarse en instrumentos de viento", correct: "C")
        ],

        "Intervalos": [
            tq("¿Cuántos semitonos tiene una tercera mayor?",
               "2", "3", "4", "5", correct: "C"),
            tq("¿Qué intervalo existe entre C y G?",
               "Tercera mayor", "Cuarta justa", "Quinta justa", "Sexta mayor", correct: "C"),
            tq("¿Cuántos semitonos tiene una octava?",
               "8", "10", "11", "12", correct: "D"),
            tq("¿Qué intervalo distingue principalmente una tríada mayor de una menor?",
               "La quinta", "La tercera", "La octava", "La segunda", correct: "B"),
            tq("¿Qué intervalo forman G y F ascendente dentro de la misma octava?",
               "Sexta mayor", "Séptima menor", "Séptima mayor", "Octava disminuida", correct: "B")
        ],

        "Ritmo, figuras y compás": [
            tq("¿Cuántas negras caben en un compás de 4/4?",
               "2", "3", "4", "8", correct: "C"),
            tq("¿Cuántas corcheas equivalen a una negra con puntillo?",
               "2", "3", "4", "6", correct: "B"),
            tq("¿Qué indica el número superior de un compás?",
               "La velocidad de la canción", "La cantidad de pulsos o subdivisiones principales por compás", "La tonalidad", "El volumen de cada tiempo", correct: "B"),
            tq("¿Qué es una síncopa?",
               "Un cambio obligatorio de tonalidad", "Un acento o ataque en una parte débil o inesperada del pulso", "Una nota tocada siempre en el primer tiempo", "Una repetición exacta de cuatro compases", correct: "B"),
            tq("¿Qué diferencia existe entre una ligadura de prolongación y una ligadura de expresión?",
               "No existe ninguna diferencia", "La primera une duraciones de la misma nota; la segunda conecta notas diferentes", "La primera cambia la tonalidad", "La segunda aumenta el tempo", correct: "B")
        ],

        "Escala mayor y tonalidades": [
            tq("¿Cuál es la estructura de tonos y semitonos de la escala mayor?",
               "T – S – T – T – S – T – T", "T – T – S – T – T – T – S", "S – T – T – S – T – T – T", "T – T – T – S – T – S – T", correct: "B"),
            tq("¿Qué notas forman la escala de C mayor?",
               "C – D – E – F – G – A – B", "C – D – E♭ – F – G – A♭ – B♭", "C – D♭ – E♭ – F – G♭ – A♭ – B♭", "C – D – E – F♯ – G – A – B", correct: "A"),
            tq("¿Qué alteración contiene G mayor?",
               "B♭", "F♯", "C♯", "E♭", correct: "B"),
            tq("¿Cuál es el séptimo grado de C mayor?",
               "A", "B", "C", "D", correct: "B"),
            tq("¿Cuántos sostenidos tiene D mayor?",
               "Ninguno", "Uno: F♯", "Dos: F♯ y C♯", "Tres: F♯, C♯ y G♯", correct: "C")
        ],

        "Escalas menores": [
            tq("¿Cuál es la fórmula de la escala menor natural?",
               "1 – 2 – 3 – 4 – 5 – 6 – 7", "1 – 2 – ♭3 – 4 – 5 – ♭6 – ♭7", "1 – ♭2 – ♭3 – 4 – ♭5 – ♭6 – ♭7", "1 – 2 – ♭3 – 4 – 5 – 6 – 7", correct: "B"),
            tq("¿Qué nota se eleva en A menor armónica?",
               "C pasa a C♯", "F pasa a F♯", "G pasa a G♯", "E pasa a E♯", correct: "C"),
            tq("¿Cuál es el relativo menor de C mayor?",
               "C menor", "A menor", "E menor", "D menor", correct: "B"),
            tq("¿Cuál es el relativo mayor de E menor?",
               "E mayor", "C mayor", "G mayor", "D mayor", correct: "C"),
            tq("¿Qué grados diferencian a la escala menor natural de su mayor paralela?",
               "♭2, ♭4 y ♭5", "♭3, ♭6 y ♭7", "♯4 y ♭7", "♭2, ♭3 y ♭6", correct: "B")
        ],

        "Escalas pentatónicas y blues": [
            tq("¿Cuál es la fórmula de la pentatónica menor?",
               "1 – 2 – 3 – 5 – 6", "1 – ♭3 – 4 – 5 – ♭7", "1 – ♭2 – 4 – ♭5 – 7", "1 – 3 – 4 – 5 – 7", correct: "B"),
            tq("¿Qué notas forman A pentatónica menor?",
               "A – B – C♯ – E – F♯", "A – C – D – E – G", "A – B♭ – D – E♭ – G", "A – C♯ – D – F – G♯", correct: "B"),
            tq("¿Qué nota añade la escala de blues menor?",
               "Segunda mayor", "Tercera mayor", "Quinta disminuida", "Séptima mayor", correct: "C"),
            tq("¿Cuál es la fórmula de la pentatónica mayor?",
               "1 – 2 – 3 – 5 – 6", "1 – ♭3 – 4 – 5 – ♭7", "1 – 3 – 4 – 6 – 7", "1 – 2 – 4 – 5 – ♭7", correct: "A"),
            tq("¿Qué relación existe entre C pentatónica mayor y A pentatónica menor?",
               "No comparten ninguna nota", "Comparten las mismas notas, pero tienen diferente centro tonal", "Solo comparten C y A", "Una contiene sostenidos y la otra bemoles", correct: "B")
        ],

        "Construcción de tríadas": [
            tq("¿Cuál es la fórmula de una tríada mayor?",
               "1 – ♭3 – 5", "1 – 3 – 5", "1 – 3 – ♯5 – 7", "1 – 4 – 5", correct: "B"),
            tq("¿Qué notas forman C mayor?",
               "C – E – G", "C – E♭ – G", "C – F – G", "C – E – G♯", correct: "A"),
            tq("¿Qué transforma una tríada mayor en menor?",
               "Bajar la quinta un semitono", "Bajar la tercera un semitono", "Elevar la fundamental", "Eliminar la quinta", correct: "B"),
            tq("¿Cuál es la fórmula de una tríada disminuida?",
               "1 – ♭3 – ♭5", "1 – 3 – ♭5", "1 – ♭3 – 5", "1 – 3 – ♯5", correct: "A"),
            tq("¿Qué nota se encuentra en el bajo en una primera inversión?",
               "La fundamental", "La tercera", "La quinta", "La séptima", correct: "B")
        ],

        "Acordes de séptima y extensiones": [
            tq("¿Cuál es la fórmula de un acorde mayor séptima?",
               "1 – 3 – 5 – 7", "1 – 3 – 5 – ♭7", "1 – ♭3 – 5 – ♭7", "1 – 3 – ♭5 – 7", correct: "A"),
            tq("¿Qué notas forman G7?",
               "G – B – D – F", "G – B♭ – D – F", "G – B – D – F♯", "G – C – D – F", correct: "A"),
            tq("¿Cuál es la fórmula de un acorde menor séptima?",
               "1 – 3 – 5 – 7", "1 – ♭3 – 5 – ♭7", "1 – ♭3 – ♭5 – 7", "1 – 3 – ♯5 – ♭7", correct: "B"),
            tq("¿Qué notas suelen definir con especial claridad la función de un acorde de séptima?",
               "Fundamental y quinta", "Tercera y séptima", "Segunda y cuarta", "Quinta y octava", correct: "B"),
            tq("¿Qué diferencia principal existe entre Cadd9 y C9?",
               "Cadd9 contiene una séptima menor obligatoria", "C9 normalmente incluye una séptima; Cadd9 no la requiere", "Cadd9 es siempre menor", "No existe diferencia", correct: "B")
        ],

        "Inversiones, voicings y sistema CAGED": [
            tq("¿Qué cambia necesariamente en una inversión?",
               "La tonalidad", "La nota más grave", "La duración", "El número de cuerdas de la guitarra", correct: "B"),
            tq("¿Qué nota está en el bajo en una segunda inversión?",
               "La fundamental", "La tercera", "La quinta", "La séptima", correct: "C"),
            tq("¿Qué representa el término voicing?",
               "La velocidad de un acorde", "La disposición específica de sus notas", "El volumen del amplificador", "El tipo de púa", correct: "B"),
            tq("¿Qué describe principalmente el sistema CAGED?",
               "Cinco afinaciones abiertas", "Cinco formas conectadas para organizar acordes y escalas en el mástil", "Cinco tipos de pastillas", "Cinco ritmos de blues", correct: "B"),
            tq("¿Cuál es la estructura básica de un power chord?",
               "Fundamental, tercera y quinta", "Fundamental y quinta, con octava opcional", "Tercera y séptima", "Fundamental y séptima mayor", correct: "B")
        ],

        "Armonización de la escala mayor": [
            tq("¿Cuál es el patrón correcto de tríadas en una tonalidad mayor?",
               "Mayor – menor – menor – mayor – mayor – menor – disminuido", "Mayor – mayor – menor – menor – mayor – disminuido – menor", "Menor – disminuido – mayor – menor – mayor – mayor – menor", "Mayor – menor – mayor – menor – mayor – menor – mayor", correct: "A"),
            tq("¿Cuál es el acorde ii de C mayor?",
               "D", "Dm", "Ddim", "D7", correct: "B"),
            tq("¿Cuál es el acorde vi de C mayor?",
               "A", "Am", "Adim", "A7", correct: "B"),
            tq("¿Qué acorde se construye sobre el séptimo grado de una escala mayor?",
               "Mayor", "Menor", "Disminuido", "Aumentado", correct: "C"),
            tq("¿Por qué son útiles los números romanos?",
               "Porque indican una digitación obligatoria", "Porque describen funciones y relaciones transportables entre acordes", "Porque sustituyen el ritmo", "Porque eliminan la necesidad de conocer las notas", correct: "B")
        ],

        "Funciones armónicas": [
            tq("¿Qué función suele representar el acorde I?",
               "Dominante", "Tónica", "Cromática", "Modulatoria obligatoria", correct: "B"),
            tq("¿Qué función suele cumplir el acorde V?",
               "Tónica", "Dominante", "Relativa menor", "Pedal", correct: "B"),
            tq("¿Qué acordes suelen tener función predominante en una tonalidad mayor?",
               "ii y IV", "I y vi", "V y vii°", "iii y V", correct: "A"),
            tq("¿Qué movimiento representa una resolución dominante típica?",
               "I hacia IV", "V hacia I", "vi hacia iii", "IV hacia ii", correct: "B"),
            tq("¿Por qué no debe determinarse la función solamente por el nombre del acorde?",
               "Porque la función depende del contexto tonal y del movimiento armónico", "Porque todos los acordes tienen la misma función", "Porque la función depende exclusivamente del amplificador", "Porque los acordes menores no tienen función", correct: "A")
        ],

        "Progresiones y cadencias": [
            tq("¿Qué movimiento forma una cadencia auténtica?",
               "IV-I", "V-I", "I-vi", "ii-IV", correct: "B"),
            tq("¿Qué movimiento forma una cadencia plagal?",
               "IV-I", "V-vi", "ii-V", "I-V", correct: "A"),
            tq("¿Qué acordes forman un ii-V-I en C mayor?",
               "Dm – G – C", "D – Gm – C", "F – G – Am", "Em – Am – D", correct: "A"),
            tq("¿Qué ocurre normalmente en una cadencia engañosa?",
               "El acorde V resuelve en un acorde distinto de I, frecuentemente vi", "El acorde I siempre pasa a IV", "Se elimina la dominante", "La canción cambia necesariamente de compás", correct: "A"),
            tq("¿Qué ventaja ofrece analizar I-V-vi-IV en lugar de C-G-Am-F?",
               "Permite transportar la relación a cualquier tonalidad", "Evita aprender los acordes", "Indica automáticamente el ritmo", "Determina qué guitarra debe utilizarse", correct: "A")
        ],

        "Arpegios y notas del acorde": [
            tq("¿Qué es un arpegio?",
               "Una escala de cinco notas", "Las notas de un acorde ejecutadas sucesivamente", "Un acorde tocado necesariamente con distorsión", "Un patrón rítmico de semicorcheas", correct: "B"),
            tq("¿Qué notas forman el arpegio de Am?",
               "A – C – E", "A – C♯ – E", "A – D – E", "A – C – F", correct: "A"),
            tq("¿Qué notas forman Cmaj7?",
               "C – E – G – B", "C – E – G – B♭", "C – E♭ – G – B♭", "C – F – G – B", correct: "A"),
            tq("¿Qué ventaja tiene resolver una frase sobre una nota del acorde?",
               "Garantiza que toda frase sea rápida", "Produce normalmente una sensación de conexión armónica", "Elimina la necesidad de ritmo", "Convierte cualquier acorde en mayor", correct: "B"),
            tq("¿Es necesario usar sweep picking para tocar un arpegio?",
               "Sí, siempre", "Solo en acordes mayores", "No; el arpegio es un concepto de notas y puede ejecutarse con distintas técnicas", "Solo con guitarra acústica", correct: "C")
        ],

        "Modos de la escala mayor": [
            tq("¿Qué modo corresponde a la escala mayor tradicional?",
               "Dórico", "Jónico", "Frigio", "Mixolidio", correct: "B"),
            tq("¿Qué característica distingue al modo dórico de la menor natural?",
               "Segunda menor", "Cuarta aumentada", "Sexta mayor", "Séptima mayor", correct: "C"),
            tq("¿Qué nota característica tiene el modo lidio respecto de la escala mayor?",
               "♭2", "♭3", "♯4", "♭7", correct: "C"),
            tq("¿Qué diferencia principal tiene mixolidio respecto de la escala mayor?",
               "♭2", "♭3", "♯4", "♭7", correct: "D"),
            tq("¿Qué se necesita para que D-E-F-G-A-B-C suene realmente como D dórico?",
               "Tocar siempre desde la nota más grave", "Establecer D como centro tonal mediante armonía, pedal, resolución o énfasis", "Utilizar una guitarra de siete cuerdas", "Tocar las notas en orden descendente", correct: "B")
        ],

        "Voice leading y conducción de voces": [
            tq("¿Cuál es un objetivo habitual del voice leading?",
               "Producir siempre los saltos más grandes", "Conectar las voces con movimientos claros y eficientes", "Tocar todos los acordes en primera posición", "Eliminar las terceras", correct: "B"),
            tq("¿Qué notas comparten C mayor y A menor?",
               "C y E", "G y B", "A y G", "D y F", correct: "A"),
            tq("¿Qué recurso facilita una conducción de voces compacta en guitarra?",
               "Utilizar únicamente power chords", "Usar inversiones y tríadas en grupos de cuerdas", "Tocar siempre las seis cuerdas", "Subir el volumen", correct: "B"),
            tq("En G7, ¿qué intervalo forman B y F?",
               "Quinta justa", "Tritono", "Tercera mayor", "Octava", correct: "B"),
            tq("En una resolución G7-C, ¿cómo tienden a moverse B y F?",
               "B hacia C y F hacia E", "B hacia A y F hacia G", "B hacia D y F hacia C", "Ambas permanecen obligatoriamente inmóviles", correct: "A")
        ],

        "Transporte y afinaciones": [
            tq("¿Qué significa transportar una progresión?",
               "Cambiar el ritmo sin cambiar los acordes", "Moverla a otra tonalidad conservando sus relaciones", "Tocar los acordes en orden inverso", "Convertir todos los acordes en menores", correct: "B"),
            tq("Si I-IV-V en C es C-F-G, ¿qué acordes forman I-IV-V en D?",
               "D-G-A", "D-F-G", "D-A-B", "D-G-Bm", correct: "A"),
            tq("¿Cuál es la afinación Drop D?",
               "D-A-D-G-B-E", "D-G-C-F-A-D", "E-A-D-G-B-D", "D-A-D-F-A-D", correct: "A"),
            tq("¿Qué cambia al bajar todas las cuerdas medio tono?",
               "Las relaciones entre las cuerdas cambian completamente", "Las formas relativas se mantienen, pero todas las notas reales bajan un semitono", "Solo cambia la primera cuerda", "Los acordes mayores se convierten en menores", correct: "B"),
            tq("¿Qué diferencia existe entre transporte y modulación?",
               "No existe diferencia", "Transportar mueve toda la pieza; modular cambia de centro tonal dentro de la música", "Modular significa cambiar de guitarra", "Transportar modifica únicamente el tempo", correct: "B")
        ],

        "Improvisación y relación acorde-escala": [
            tq("¿Qué notas suelen proporcionar puntos de resolución claros?",
               "Notas completamente ajenas a la armonía", "Notas del acorde", "Únicamente notas cromáticas", "Solo la segunda menor", correct: "B"),
            tq("¿Qué nota diferencia claramente un acorde mayor de uno menor?",
               "La fundamental", "La tercera", "La quinta justa", "La octava", correct: "B"),
            tq("Sobre G7, ¿qué nota expresa la séptima menor del acorde?",
               "E", "F", "F♯", "A", correct: "B"),
            tq("¿Qué es un motivo?",
               "Una idea musical breve que puede repetirse y desarrollarse", "Una escala ejecutada siempre completa", "Una única nota sin función", "Un cambio de amplificador", correct: "A"),
            tq("¿Qué práctica mejora más la relación entre improvisación y armonía?",
               "Memorizar una figura y tocarla sobre cualquier acorde", "Localizar las notas de cada acorde y dirigir frases hacia ellas", "Evitar escuchar la base", "Tocar únicamente desde el primer traste", correct: "B")
        ],

        "Recursos armónicos no diatónicos": [
            tq("¿Cuál es V/V en C mayor?",
               "D7", "Fm", "Am", "Bdim", correct: "A"),
            tq("¿Hacia qué acorde tiende a resolver D7 en C mayor?",
               "C", "Dm", "G", "Am", correct: "C"),
            tq("¿Qué es intercambio modal?",
               "Cambiar obligatoriamente de compás", "Tomar acordes del modo o tonalidad paralela", "Tocar dos escalas simultáneamente", "Sustituir todas las notas por cromatismos", correct: "B"),
            tq("En C mayor, ¿cuál puede ser un acorde prestado de C menor?",
               "Fm", "G", "Am", "Em", correct: "A"),
            tq("¿Qué diferencia a una tonicización breve de una modulación estable?",
               "La tonicización enfatiza temporalmente otro acorde; la modulación establece un nuevo centro tonal", "La tonicización cambia siempre de tempo", "La modulación dura exactamente un compás", "No existe diferencia", correct: "A")
        ],

        "Oído, transcripción, lectura y sonido eléctrico": [
            tq("¿Qué información ofrece principalmente una tablatura?",
               "Posiciones de cuerdas y trastes", "Únicamente la tonalidad", "El modelo de guitarra", "La configuración exacta del amplificador", correct: "A"),
            tq("¿Qué práctica desarrolla directamente el oído aplicado al instrumento?",
               "Memorizar figuras sin escucharlas", "Cantar una frase y localizarla después en la guitarra", "Aumentar la ganancia", "Cambiar las cuerdas semanalmente", correct: "B"),
            tq("¿Qué pastilla suele ofrecer un sonido más brillante y definido?",
               "La pastilla del puente", "La pastilla del mástil", "Ninguna pastilla produce diferencias", "La pastilla más alejada de las cuerdas", correct: "A"),
            tq("¿Qué efecto general produce aumentar la ganancia?",
               "Reduce todos los armónicos", "Añade saturación y normalmente aumenta la compresión", "Cambia automáticamente la tonalidad", "Elimina la necesidad de muting", correct: "B"),
            tq("¿Cuál afirmación sobre el orden de los efectos es más correcta?",
               "Existe un único orden obligatorio para todos los estilos", "El orden no modifica nunca el sonido", "Existen órdenes habituales, pero pueden alterarse intencionalmente según el resultado buscado", "El delay debe colocarse siempre antes de la guitarra", correct: "C")
        ]
    ]
}
